// export default function App() {
//   const [name, setName] = useState(''); //I added a state for the text input and dont know why it autogenerated the text but aight

//   return (
//     <View style={s.screen}>
//         <Image
//             source={{ uri: 'https://scontent.fdvo5-1.fna.fbcdn.net/v/t39.30808-6/342504767_1296321470970546_34225895670814679_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeGpC0YaphsTPh6-tG-byLoMXoEDUv1XquRegQNS_Veq5JgIHn0aSCTpTbzHFIS75N2lm2p2JQLnfgJUH5V5ciW1&_nc_ohc=fJ1nn5f7wBwQ7kNvwFnHKB1&_nc_oc=AdqSeSF8w0fpwklQiihOU7-5DUBhnLnKDyj_HzrEjrD-RquRIdmR31rz_m7uikVwob8&_nc_zt=23&_nc_ht=scontent.fdvo5-1.fna&_nc_gid=9a8iEGFMUZ4lHbq86m4YVQ&_nc_ss=7b2a8&oh=00_Af5RYfs8i2QW7NxTHhsVd_-bd0mSefJj-NPzkoOZcv25Pg&oe=6A0DAFE6' }} //I changed the image to my facebook profile picture
//             style={s.photo} 
//         />
//         <Text style={s.name}>Adam Alexis Yahya</Text> {/*I changed it to my name */}
//         <Text style={s.bio}>MMA Student • CS126</Text> {/*I changed it to my bio */}
    
//       <TextInput
//         placeholder="Type something..."
//         onChangeText={setName}
//         style={{
//           height: 40,
//           margin: 12,
//           borderWidth: 1,
//           padding: 10,
//           width: 200,
//         }}
//       />

//       <Text style={s.name}>
//         Konbanwaaaa, {name}!
//       </Text>
//       {/*<Text style={{fontSize: 18, color: '#333'}}>{name}</Text> {/*I added a text input and made it so that it changes the text below it to whatever you type in the text input */} 
//     </View>
//   );
// }

// const s = StyleSheet.create({
//     screen: {flex:1, backgroundColor: '#d2cdb7', alignItems: 'center', justifyContent: 'center'}, //I added a way to change the background color
//     photo: {width: 120, height: 120, borderRadius: 60}, 
//     name: {fontSize: 24, color: '#181818', fontWeight: 'bold', marginTop: 16, fontFamily: 'Papyrus'}, // I also added a way to change the color of the font
//     bio: {fontSize: 16, color: '#656464'}, // I also added a way to change the color of the font on this part as well
// });

//old code on top

// new code below
// Date of change: 01/05/2026
// Date of change: 09/05/2026 (M1 Lecture Summative)
// Date of change: 16/05/2026 (M1 Lab Summative)


import { useState } from 'react'; //I added useState for the text input
import { View, Text, TextInput, Image, StyleSheet, Button, ScrollView} from 'react-native'; //I changed the import to whats in the image
import { useFonts } from 'expo-font'; //Wanted to experiment with custom fonts from games but wasnt readable so I just used papyrus instead

export default function App() {
  const [name, setName] = useState(''); //I added a state for the text input and dont know why it autogenerated the text but aight
  const [count, setCount] = useState(0); //button thingy
  
  const message =
    count > 0
      ?`${name}, you smashed ${count} times!`
      : "Tap the + button to smash!";
      
  return (

    
    <ScrollView contentContainerStyle={styles.container}> {/*changed it to styles*/}
      {/*new Profile Image*/}
      <Image source= {{ uri: 'https://scontent.fdvo5-1.fna.fbcdn.net/v/t39.30808-6/342504767_1296321470970546_34225895670814679_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeGpC0YaphsTPh6-tG-byLoMXoEDUv1XquRegQNS_Veq5JgIHn0aSCTpTbzHFIS75N2lm2p2JQLnfgJUH5V5ciW1&_nc_ohc=fJ1nn5f7wBwQ7kNvwFnHKB1&_nc_oc=AdqSeSF8w0fpwklQiihOU7-5DUBhnLnKDyj_HzrEjrD-RquRIdmR31rz_m7uikVwob8&_nc_zt=23&_nc_ht=scontent.fdvo5-1.fna&_nc_gid=9a8iEGFMUZ4lHbq86m4YVQ&_nc_ss=7b2a8&oh=00_Af5RYfs8i2QW7NxTHhsVd_-bd0mSefJj-NPzkoOZcv25Pg&oe=6A0DAFE6' }} style={styles.image} />
      {/*new input*/}
      <TextInput placeholder="Who are you?" onChangeText={setName} style={styles.input} />
      {/*new greeting*/}
      <Text style={styles.bold}>{name === '' ? 'Konbanwaaaa! ' : `Konbanwaaaa,` + ' ' + `${name}!`}</Text>
      {/*counter message*/}
      <Text style={styles.normal}>{message}</Text>
      {/*counter buttonnnn*/}
      <View style={styles.buttonContainer}>
        <Button title="+" onPress={() => setCount(count + 1)} />
        <Button title="-" onPress={() => setCount(count - 1)} />
        <Button title="Reset" onPress={() => setCount(0)} />
      </View>
    </ScrollView>
  );
} // complete overhaul of the previous code to make it look cleaner along with the counter button
  // I dont why but yes just to follow the format but very tiring to arrange unless I used ai which I realized late
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#d2cdb7',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    screen: {
        flex: 1,
        backgroundColor: '#d2cdb7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: 120,
        height: 120,
        borderRadius: 60,
    },
    input: {
        fontSize: 24,
        color: '#181818',
        fontWeight: 'bold',
        marginTop: 16,
        fontFamily: 'Papyrus',
        borderWidth: 1,
        borderColor: '#656464',
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    bold: {
        fontSize: 24,
        color: '#181818',
        fontWeight: 'bold',
        marginTop: 16,
        fontFamily: 'Papyrus',
    },
    normal: {
        fontSize: 16,
        color: '#656464',
    },
    buttonContainer: {
        marginTop: 20,
        justifyContent: 'space-between', 
        width: '60%',
    },

});

// only systems with papyrus font will be able to see the font change so it won't appear in phone