// Date of change: 16/05/2026 (M1 Lab Summative)


// import { useState } from 'react'; //I added useState for the text input
// import { View, Text, TextInput, Image, StyleSheet, Button, ScrollView} from 'react-native'; //I changed the import to whats in the image
// import { useFonts } from 'expo-font'; //Wanted to experiment with custom fonts from games but wasnt readable so I just used papyrus instead

// export default function App() {
//   const [name, setName] = useState(''); //I added a state for the text input and dont know why it autogenerated the text but aight
//   const [count, setCount] = useState(0); //button thingy
  
//   const message =
//     count > 0
//       ?`${name}, you smashed ${count} times!`
//       : "Tap the + button to smash!";
      
//   return (

    
//     <ScrollView contentContainerStyle={styles.container}> {/*changed it to styles*/}
//       {/*new Profile Image*/}
//       <Image source= {{ uri: 'https://scontent.fdvo5-1.fna.fbcdn.net/v/t39.30808-6/342504767_1296321470970546_34225895670814679_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeGpC0YaphsTPh6-tG-byLoMXoEDUv1XquRegQNS_Veq5JgIHn0aSCTpTbzHFIS75N2lm2p2JQLnfgJUH5V5ciW1&_nc_ohc=fJ1nn5f7wBwQ7kNvwFnHKB1&_nc_oc=AdqSeSF8w0fpwklQiihOU7-5DUBhnLnKDyj_HzrEjrD-RquRIdmR31rz_m7uikVwob8&_nc_zt=23&_nc_ht=scontent.fdvo5-1.fna&_nc_gid=9a8iEGFMUZ4lHbq86m4YVQ&_nc_ss=7b2a8&oh=00_Af5RYfs8i2QW7NxTHhsVd_-bd0mSefJj-NPzkoOZcv25Pg&oe=6A0DAFE6' }} style={styles.image} />
//       {/*new input*/}
//       <TextInput placeholder="Who are you?" onChangeText={setName} style={styles.input} />
//       {/*new greeting*/}
//       <Text style={styles.bold}>{name === '' ? 'Konbanwaaaa! ' : `Konbanwaaaa,` + ' ' + `${name}!`}</Text>
//       {/*counter message*/}
//       <Text style={styles.normal}>{message}</Text>
//       {/*counter buttonnnn*/}
//       <View style={styles.buttonContainer}>
//         <Button title="+" onPress={() => setCount(count + 1)} />
//         <Button title="-" onPress={() => setCount(count - 1)} />
//         <Button title="Reset" onPress={() => setCount(0)} />
//       </View>
//     </ScrollView>
//   );
// } // complete overhaul of the previous code to make it look cleaner along with the counter button
//   // I dont why but yes just to follow the format but very tiring to arrange unless I used ai which I realized late
// const styles = StyleSheet.create({
//     container: {
//         flex: 1,
//         backgroundColor: '#d2cdb7',
//         alignItems: 'center',
//         justifyContent: 'center',
//         padding: 20,
//     },
//     screen: {
//         flex: 1,
//         backgroundColor: '#d2cdb7',
//         alignItems: 'center',
//         justifyContent: 'center',
//     },
//     image: {
//         width: 120,
//         height: 120,
//         borderRadius: 60,
//     },
//     input: {
//         fontSize: 24,
//         color: '#181818',
//         fontWeight: 'bold',
//         marginTop: 16,
//         fontFamily: 'Papyrus',
//         borderWidth: 1,
//         borderColor: '#656464',
//         borderRadius: 8,
//         paddingVertical: 8,
//         paddingHorizontal: 16,
//     },
//     bold: {
//         fontSize: 24,
//         color: '#181818',
//         fontWeight: 'bold',
//         marginTop: 16,
//         fontFamily: 'Papyrus',
//     },
//     normal: {
//         fontSize: 16,
//         color: '#656464',
//     },
//     buttonContainer: {
//         marginTop: 20,
//         justifyContent: 'space-between', 
//         width: '60%',
//     },

// });

// // only systems with papyrus font will be able to see the font change so it won't appear in phone
// old code on top

import { View, Text, FlatList, StyleSheet, TouchableOpacity } from 'react-native';
import { NavigationIndependentTree } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

// ─── Coffee Menu Data ────────────────────────────────────────────────────────
const menuItems = [
  { id: '1', category: 'Hot Drinks',  name: 'Americano',   price: '₱120', desc: 'Bold and strong black coffee brewed with espresso shots.' },
  { id: '2', category: 'Hot Drinks',  name: 'Cappuccino',  price: '₱150', desc: 'Classic Italian coffee with equal parts espresso, steamed milk, and foam.' },
  { id: '3', category: 'Hot Drinks',  name: 'Latte',       price: '₱160', desc: 'Smooth espresso blended with creamy steamed milk.' },
  { id: '4', category: 'Cold Drinks', name: 'Iced Coffee', price: '₱130', desc: 'Chilled brewed coffee served over ice for a refreshing kick.' },
  { id: '5', category: 'Cold Drinks', name: 'Frappuccino', price: '₱175', desc: 'Blended iced coffee drink topped with whipped cream.' },
  { id: '6', category: 'Dessert', name: 'Brownie', price: '₱35', desc: 'Blended iced coffee drink topped with whipped cream.' },
  { id: '7', category: 'Dessert', name: 'Donut', price: '₱50', desc: 'Blended iced coffee drink topped with whipped cream.' },
  { id: '8', category: 'Dessert', name: 'Slice of Cake', price: '₱220', desc: 'Blended iced coffee drink topped with whipped cream.' },
];

// ─── Stack Navigator Setup ───────────────────────────────────────────────────
// createStackNavigator() creates a "stack" of screens.
// Think of it like a stack of cards — you push a card when you go forward,
// and pop it off when you press Back.
const Stack = createNativeStackNavigator();

// ─── Home Screen (Coffee Menu) ───────────────────────────────────────────────
function HomeScreen({ navigation }: any) {
  return (
    <View style={styles.container}>
      <Text style={styles.heading}>☕ Coffee Shop Menu</Text>

      {/* FlatList renders the menuItems array as a scrollable list */}
      <FlatList
        data={menuItems}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <TouchableOpacity
            style={styles.item}
            activeOpacity={0.75}
            onPress={() => navigation.navigate('Detail', { coffee: item })}
          >
            <Text style={styles.category}>{item.category}</Text>
            <Text style={styles.name}>{item.name}</Text>
            <Text style={styles.price}>{item.price}</Text>
          </TouchableOpacity>
        )}
      />
    </View>
  );
}

// ─── Detail Screen ───────────────────────────────────────────────────────────
function DetailScreen({ route, navigation }: any) {

  // route.params contains the data we passed when calling navigation.navigate()
  const { coffee } = route.params;

  return (
    <View style={styles.detailContainer}>
      <Text style={styles.detailCategory}>{coffee.category}</Text>
      <Text style={styles.detailName}>{coffee.name}</Text>
      <Text style={styles.detailPrice}>{coffee.price}</Text>
      <Text style={styles.detailDesc}>{coffee.desc}</Text>

      {/* navigation.goBack() pops this screen off and returns to HomeScreen */}
      <TouchableOpacity
        style={styles.backButton}
        activeOpacity={0.8}
        onPress={() => navigation.goBack()}
      >
        <Text style={styles.backButtonText}>← Back to Menu</Text>
      </TouchableOpacity>
    </View>
  );
}

// ─── App (Navigation Container) ─────────────────────────────────────────────
// NavigationIndependentTree is needed because Expo Router already has its own
// navigator running. This tells React Navigation to treat our Stack as
// a separate, independent navigation tree so they don't conflict.
export default function App() {
  return (
    <NavigationIndependentTree>
      <Stack.Navigator
        screenOptions={{
          headerStyle: { backgroundColor: '#3E1F00' },
          headerTintColor: '#F5E6D3',
          headerTitleStyle: { fontWeight: 'bold' },
        }}
      >
        {/* Register our two screens with the Stack */}
        <Stack.Screen name="Menu"   component={HomeScreen}   options={{ title: '☕ Rainbow Coffee'}} />
        <Stack.Screen name="Detail" component={DetailScreen} options={{ title: 'Coffee Details', headerLeft: () => null }} />
      </Stack.Navigator>
    </NavigationIndependentTree>
  );
}

// ─── Styles ──────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({

  // Home Screen
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FDF6EE',
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#3E1F00',
  },
  item: {
    backgroundColor: '#FFF8F2',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#560ec1',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  category: {
    fontSize: 12,
    color: '#6c6b6b',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  name: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3E1F00',
  },
  price: {
    fontSize: 14,
    color: '#C1440E',
    marginTop: 4,
  },

  // Detail Screen
  detailContainer: {
    flex: 1,
    padding: 28,
    backgroundColor: '#FDF6EE',
    justifyContent: 'center',
  },
  detailCategory: {
    fontSize: 13,
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  detailName: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#3E1F00',
    marginBottom: 8,
  },
  detailPrice: {
    fontSize: 22,
    color: '#C1440E',
    fontWeight: '600',
    marginBottom: 20,
  },
  detailDesc: {
    fontSize: 16,
    color: '#555',
    lineHeight: 24,
    marginBottom: 40,
  },
  backButton: {
    backgroundColor: '#3E1F00',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 10,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#FDF6EE',
    fontSize: 16,
    fontWeight: '600',
  },

});