// import { Image } from 'expo-image';
// import { Platform, StyleSheet } from 'react-native';

// import { HelloWave } from '@/components/hello-wave';
// import ParallaxScrollView from '@/components/parallax-scroll-view';
// import { ThemedText } from '@/components/themed-text';
// import { ThemedView } from '@/components/themed-view';
// import { Link } from 'expo-router';

// export default function HomeScreen() {
//   return (
//     <ParallaxScrollView
//       headerBackgroundColor={{ light: '#A1CEDC', dark: '#1D3D47' }}
//       headerImage={
//         <Image
//           source={require('@/assets/images/partial-react-logo.png')}
//           style={styles.reactLogo}
//         />
//       }>
//       <ThemedView style={styles.titleContainer}>
//         <ThemedText type="title">HELLOOOOO!</ThemedText>
//         <HelloWave />
//       </ThemedView>
//       <ThemedView style={styles.stepContainer}>
//         <ThemedText type="subtitle">Step 1: Try it</ThemedText>
//         <ThemedText>
//           Edit <ThemedText type="defaultSemiBold">app/(tabs)/index.tsx</ThemedText> to see changes.
//           Press{' '}
//           <ThemedText type="defaultSemiBold">
//             {Platform.select({
//               ios: 'cmd + d',
//               android: 'cmd + m',
//               web: 'F12',
//             })}
//           </ThemedText>{' '}
//           to open developer tools.
//         </ThemedText>
//       </ThemedView>
//       <ThemedView style={styles.stepContainer}>
//         <Link href="/modal">
//           <Link.Trigger>
//             <ThemedText type="subtitle">Step 2: Explore</ThemedText>
//           </Link.Trigger>
//           <Link.Preview />
//           <Link.Menu>
//             <Link.MenuAction title="Action" icon="cube" onPress={() => alert('Action pressed')} />
//             <Link.MenuAction
//               title="Share"
//               icon="square.and.arrow.up"
//               onPress={() => alert('Share pressed')}
//             />
//             <Link.Menu title="More" icon="ellipsis">
//               <Link.MenuAction
//                 title="Delete"
//                 icon="trash"
//                 destructive
//                 onPress={() => alert('Delete pressed')}
//               />
//             </Link.Menu>
//           </Link.Menu>
//         </Link>

//         <ThemedText>
//           {`Tap the Explore tab to learn more about what's included in this starter app.`}
//         </ThemedText>
//       </ThemedView>
//       <ThemedView style={styles.stepContainer}>
//         <ThemedText type="subtitle">Step 3: Get a fresh start</ThemedText>
//         <ThemedText>
//           {`When you're ready, run `}
//           <ThemedText type="defaultSemiBold">npm run reset-project</ThemedText> to get a fresh{' '}
//           <ThemedText type="defaultSemiBold">app</ThemedText> directory. This will move the current{' '}
//           <ThemedText type="defaultSemiBold">app</ThemedText> to{' '}
//           <ThemedText type="defaultSemiBold">app-example</ThemedText>.
//         </ThemedText>
//       </ThemedView>
//     </ParallaxScrollView>
//   );
// }

// const styles = StyleSheet.create({
//   titleContainer: {
//     flexDirection: 'row',
//     alignItems: 'center',
//     gap: 8,
//   },
//   stepContainer: {
//     gap: 8,
//     marginBottom: 8,
//   },
//   reactLogo: {
//     height: 178,
//     width: 290,
//     bottom: 0,
//     left: 0,
//     position: 'absolute',
//   },
// });

//old code on top

// new code below
// Date of change: 01/05/2026
// Date of change: 09/05/2026 (Lecture Summative)


import { useState } from 'react'; //I added useState for the text input
import { View, Text, TextInput, Image, StyleSheet} from 'react-native'; //I changed the import to whats in the image
import { useFonts } from 'expo-font';

export default function App() {
  const [name, setName] = useState(''); //I added a state for the text input and dont know why it autogenerated the text but aight

  return (
    <View style={s.screen}>
        <Image
            source={{ uri: 'https://scontent.fdvo5-1.fna.fbcdn.net/v/t39.30808-6/342504767_1296321470970546_34225895670814679_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeGpC0YaphsTPh6-tG-byLoMXoEDUv1XquRegQNS_Veq5JgIHn0aSCTpTbzHFIS75N2lm2p2JQLnfgJUH5V5ciW1&_nc_ohc=fJ1nn5f7wBwQ7kNvwFnHKB1&_nc_oc=AdqSeSF8w0fpwklQiihOU7-5DUBhnLnKDyj_HzrEjrD-RquRIdmR31rz_m7uikVwob8&_nc_zt=23&_nc_ht=scontent.fdvo5-1.fna&_nc_gid=9a8iEGFMUZ4lHbq86m4YVQ&_nc_ss=7b2a8&oh=00_Af5RYfs8i2QW7NxTHhsVd_-bd0mSefJj-NPzkoOZcv25Pg&oe=6A0DAFE6' }} //I changed the image to my facebook profile picture
            style={s.photo} 
        />
        <Text style={s.name}>Adam Alexis Yahya</Text> {/*I changed it to my name */}
        <Text style={s.bio}>MMA Student • CS126</Text> {/*I changed it to my bio */}
    
      <TextInput
        placeholder="Type something..."
        onChangeText={setName}
        style={{
          height: 40,
          margin: 12,
          borderWidth: 1,
          padding: 10,
          width: 200,
        }}
      />

      <Text style={s.name}>
        Konbanwaaaa, {name}!
      </Text>
      {/*<Text style={{fontSize: 18, color: '#333'}}>{name}</Text> {/*I added a text input and made it so that it changes the text below it to whatever you type in the text input */} 
    </View>
  );
}

const s = StyleSheet.create({
    screen: {flex:1, backgroundColor: '#d2cdb7', alignItems: 'center', justifyContent: 'center'}, //I added a way to change the background color
    photo: {width: 120, height: 120, borderRadius: 60}, 
    name: {fontSize: 24, color: '#181818', fontWeight: 'bold', marginTop: 16, fontFamily: 'Papyrus'}, // I also added a way to change the color of the font
    bio: {fontSize: 16, color: '#656464'}, // I also added a way to change the color of the font on this part as well
});